stoqs/stoqs/urls.py
# -*- coding: utf-8 -*-


from django.conf import settings
from django.urls import re_path
from django.conf.urls.static import static
from stoqs.views.wms import showActivityWMS, showActivitiesWMS, showParametersWMS, showPlatformsWMS
from stoqs.views import (showActivityResource, showActivityParameter, showActivityType,
                         showActivity, showAnalysisMethod, showCampaignResource,
                         showCampaign, showInstantPoint, showMeasuredParameterResource,
                         showMeasurement, showParameterGroupParameter, showParameterGroup,
                         showParameterResource, showParameter, showPlatformResource,
                         showPlatformType, showPlatform, showResourceResource,
                         showResourceType, showResource, showSampleType, showSamplePurpose,
                         showSampleResource, showSample, showSimpleDepthTime, showNominalLocation)
from stoqs.views.app import (showMeasuredParameter, showSampledParameter,
                             showActivityParameterHistogram, showResourceActivity,
                             showSampleDT, showQuickLookPlots)
from stoqs.views.query import queryData, queryMap, queryUI
from stoqs.views.management import showCampaigns, showDatabase, showActivitiesMBARICustom
from stoqs.views.permalinks import generate_permalink, load_permalink
from stoqs.views.parameterinfo import parameterinfo

app_name = 'stoqs'

# The database alias (the key of the DATABASES dictionary) will prefix all of our requests
pre = r'^(?P<dbAlias>[^/]+)/'

# format is one of: 'html', 'csv', 'kml', 'json', 'parquet', 'estimate'
formatPat = r'(?P<fmt>[^/]{0,8})'

urlpatterns = [
    # New Map interfaces with inheritence of bootstrap template
    re_path(pre + r'activityWMS$', showActivityWMS, {}, name='show-activity-wms'),

    # Map interfaces
    re_path(pre + r'activitiesWMS$', showActivitiesWMS, {}, name='show-activities-wms'),
    re_path(pre + r'parametersWMS$', showParametersWMS, {}, name='show-parameters-wms'),
    re_path(pre + r'platformsWMS$', showPlatformsWMS, {}, name='show-platforms-wms'),

    # All STOQS objects - full object queries with .json, .xml, .html, and .csv responses
    # Could be replaced with a REST API app,
    re_path(pre + r'api/activityresource.?' + formatPat, showActivityResource,  {}, name='show-activityresource'),
    re_path(pre + r'api/activityparameter.?' + formatPat, showActivityParameter, {}, name='show-activityparameter'),
    re_path(pre + r'api/activitytype.?' + formatPat, showActivityType,      {}, name='show-activitytype'),
    re_path(pre + r'api/activity.?' + formatPat, showActivity,          {}, name='show-activity'),
    re_path(pre + r'api/analysismethod.?' + formatPat, showAnalysisMethod,    {}, name='show-analysismethod'),
    re_path(pre + r'api/campaignresource.?' + formatPat,
            showCampaignResource,          {}, name='show-campaignresource'),
    re_path(pre + r'api/campaign.?' + formatPat, showCampaign,          {}, name='show-campaign'),
    re_path(pre + r'api/instantpoint.?' + formatPat, showInstantPoint,      {}, name='show-instantpoint'),
    re_path(pre + r'api/measuredparameterresource.?' + formatPat,
            showMeasuredParameterResource,  {}, name='show-measuredparameterresource'),
    re_path(pre + r'api/measurement.?' + formatPat, showMeasurement,       {}, name='show-measurement'),
    re_path(pre + r'api/parametergroupparameter.?' + formatPat,
            showParameterGroupParameter,    {}, name='show-parametergroupparameter'),
    re_path(pre + r'api/parametergroup.?' + formatPat, showParameterGroup,    {}, name='show-parametergroup'),
    re_path(pre + r'api/parameterresource.?' + formatPat, showParameterResource, {}, name='show-parameterresource'),
    re_path(pre + r'api/parameter.?' + formatPat, showParameter,         {}, name='show-parameter'),
    re_path(pre + r'api/platformresource.?' + formatPat, showPlatformResource,  {}, name='show-platformresource'),
    re_path(pre + r'api/platformtype.?' + formatPat, showPlatformType,      {}, name='show-platformtype'),
    re_path(pre + r'api/platform.?' + formatPat, showPlatform,          {}, name='show-platform'),
    re_path(pre + r'api/resourceresource.?' + formatPat, showResourceResource,  {}, name='show-resourceresource'),
    re_path(pre + r'api/resourcetype.?' + formatPat, showResourceType,      {}, name='show-resourcetype'),
    re_path(pre + r'api/resource.?' + formatPat, showResource,          {}, name='show-resource'),
    re_path(pre + r'api/sampletype.?' + formatPat, showSampleType,        {}, name='show-sampletype'),
    re_path(pre + r'api/samplepurpose.?' + formatPat, showSamplePurpose,     {}, name='show-samplepuspose'),
    re_path(pre + r'api/sampleresource.?' + formatPat, showSampleResource,    {}, name='show-sampleresource'),
    re_path(pre + r'api/sample.?' + formatPat, showSample,            {}, name='show-sample'),
    re_path(pre + r'api/simpledepthtime.?' + formatPat, showSimpleDepthTime,   {}, name='show-simpledepthtime'),
    re_path(pre + r'api/nominallocation.?' + formatPat, showNominalLocation,   {}, name='show-nominallocation'),

    # Requests that override BaseOutputer
    re_path(pre + r'api/measuredparameter.?' + formatPat, showMeasuredParameter,  {}, name='show-measuredparmeter'),
    re_path(pre + r'api/sampledparameter.?' + formatPat, showSampledParameter,  {}, name='show-sampledparmeter'),
    re_path(pre + r'api/activityparameterhistogram.?' + formatPat,
            showActivityParameterHistogram,  {}, name='show-aph'),
    re_path(pre + r'api/resourceactivity.?' + formatPat, showResourceActivity,  {}, name='show-resourceactivity'),

    re_path(pre + r'sampledatatable.?' + formatPat, showSampleDT,      {}, name='show-sample-datatable'),
    re_path(pre + r'quicklookplots', showQuickLookPlots,  {}, name='show-quicklookplots'),

    # URL For Chander's STOQSQManager related views
    re_path(pre + r'query/summary/$', queryData, {}, name='stoqs-query-summary'),
    re_path(pre + r'query/map/$', queryMap, {}, name='stoqs-query-map'),
    re_path(pre + r'query/', queryUI, {}, name='stoqs-query-ui'),

    # Management, base of campaign, etc.
    re_path(r'campaigns.(?P<fmt>[^/]{3,5})$', showCampaigns, {}, name='show-campaigns'),
    re_path(pre + r'mgmt$', showDatabase, {}, name='show-database'),
    re_path(pre + r'activitiesMBARICustom$', showActivitiesMBARICustom, {}, name='show-activities'),

    # WFS - Tesing for exposing Sample data to the OpenLayers map
    # Prerequisites:
    #   su -y 'yum install libxml2-devel libxml2 libxslt-devel libxslt'
    #   pip install lxml
    #   pip install -e git+https://github.com/JeffHeard/ga_ows.git#egg=ga_ows
    #   export LD_LIBRARY_PATH='/usr/local/lib:$LD_LIBRARY_PATH' && python manage.py runserver 0.0.0.0:8000
    # re_path(pre + r'wfs/?', WFS.as_view(
    # models=[m.Sample],          # everything but this is optional.
    # title='STOQS Sample WFS',
    # provider_name='MBARI',
    # )),

    # If nothing above matches show the query interface if a dbalias is specified, otherwise show the campaigns
    re_path(pre + '$', queryUI, {}, name='base-campaign'),

    # Views related to generating permalinks for later use.
    re_path(pre + 'generate_permalink/', generate_permalink, {}, name='generate_permalink'),
    re_path(pre + 'permalink/(?P<pid>[^/]*)/', load_permalink, {}, name='load_permalink'),

    # Feed data for parameterinfo-popup
    re_path(pre + 'parameterinfo/(?P<pid>[^/]*)/', parameterinfo, {}, name='parameterinfo'),

    re_path('^$', showCampaigns, {}, name='show-default'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stoqs/stoqs/views/management.py
#!/usr/bin/env python

__author__ = "Mike McCann"
__copyright__ = "Copyright 2012, MBARI"
__credits__ = ["Chander Ganesan, Open Technology Group"]
__license__ = "GPL"
__version__ = "$Revision: 12294 $".split()[1]
__maintainer__ = "Mike McCann"
__email__ = "mccann at mbari.org"
__status__ = "Development"
__doc__ = '''

View functions that are related to managing the stoqs databases.

Mike McCann
MBARI Jan 9, 2012

@var __date__: Date of last svn commit
@undocumented: __doc__ parser
@author: __author__
@status: __status__
@license: __license__
'''

from django.shortcuts import render
from django.template import RequestContext
from django.conf import settings
from django.db import DatabaseError, connections
from django.http import HttpResponse
from stoqs.utils import encoders
import stoqs.models as mod
from datetime import datetime, timedelta
import socket
import logging
import json
import sys

logger = logging.getLogger(__name__)


class Act():
    '''A tiny class to hold all the information for an Activity that includes perhaps additional data from other
    parts of the model. The types are simple things (characters and numbers) that can appear in a web page.
    '''

    m_query = ''
    mp_query = ''
    id = 0
    campaign = ''
    platform = ''
    activitytype = ''
    name = ''
    comment = ''
    platformName = ''
    startdate = None
    enddate = None

    mCount = 0
    mpCount = 0
    parameters = ''
    links = ''


def showDatabase(request):
    '''Present summary view of the database. Show list of Activities, number of measured_paramaters, parameter names, platforms, etc.
    Offer ability to delete Activities.
    '''

    aList = mod.Activity.objects.all().order_by('startdate')

    actList = []
    for a in aList:
        qs_m = mod.Measurement.objects.filter(instantpoint__activity__id=a.id)
        qs_mp = mod.MeasuredParameter.objects.filter(measurement__instantpoint__activity__id=a.id)
        act = Act()
        if a.campaign:
            act.campaignName = a.campaign.name
        if a.platform:
            act.platformName = a.platform.name
        if a.activitytype:
            act.activityTypeName = a.activitytype.name

        act.m_query = str(qs_m.query)
        act.mp_query = str(qs_mp.query)
        act.id = a.id
        act.name = a.name
        act.comment = a.comment
        act.startdate = a.startdate
        act.isostartdate = a.startdate.strftime('%Y%m%dT%H%M%S')
        if a.enddate:
            act.enddate = a.enddate
            act.isoenddate = a.enddate.strftime('%Y%m%dT%H%M%S')

        act.mCount = qs_m.count()
        act.mpCount = qs_mp.count()
        act.parameters = ''
        actList.append(act)

    pList = mod.Parameter.objects.all().order_by('name')

    return render(request, 'management.html', context={'dbAlias': request.META['dbAlias'],
                                                       'actList': actList,
                                                       'pList': pList,
                                                       }
                  )

    # End showDatabase()


def showCampaigns(request, format=None):
    '''
    Present list of Campaigns from scanning the DATABASES dictionary from settings.
    '''

    dbAliases = list(settings.DATABASES.keys())
    logger.debug("DATABASES")
    logger.debug(settings.DATABASES)
    logger.debug("DATABASES.keys()")
    logger.debug(list(settings.DATABASES.keys()))

    # Data structure hash of lists.  Possible to have multiple campaigns in a database
    cHash = {}
    rHash = {}
    for dbAlias in list(settings.DATABASES.keys()):
        # Initialize Campaign and Resource hash lists
        cHash[dbAlias] = []
        rHash[dbAlias] = []

    for dbAlias in list(settings.DATABASES.keys()):
        try:
            logger.debug("Getting Campaign from dbAlias = %s", dbAlias)
            cqs = mod.Campaign.objects.using(dbAlias).all()
            for c in cqs:
                logger.debug("Appending campaign name = %s to cHash with key (dbAlias) = %s", c.name, dbAlias)
                cHash[dbAlias].append(c)
                r = {}
                for cr in mod.CampaignResource.objects.using(dbAlias).filter(campaign=c):
                    r[cr.resource.name] = cr.resource.value
                rHash[dbAlias].append(r)
        except (mod.Campaign.DoesNotExist, mod.Resource.DoesNotExist):
            logger.warn("Database alias %s does not exist", dbAlias)
            continue
        except DatabaseError:
            # Will happen if database defined in privateSettings does not exist yet
            logger.warn("Database alias %s returns django.db.DatabaseError", dbAlias)
            continue

        # Close the database connection, before connecting to the next database
        connections.close_all()

    # Create a hash keyed by startdate of the dbAliases and campaigns so that we display a time sorted list of campaigns
    timeSortHash = {}
    dummyTime = datetime(1970, 1, 1)
    for k in list(cHash.keys()):
        logger.debug('k = %s', k)
        for c, r in zip(cHash[k], rHash[k]):
            logger.debug('c.name = %s', c.name)
            # Use combination of dbAlias and startdate as different dbAlias's can have the same startdate
            if c.startdate:
                key = str(c.startdate) + '_' + c.name
                timeSortHash[key] = {k: (c, r)}
                logger.debug("Set timeSortHash['%s'] = %s", key, {k: (c, r)})
            else:
                # Put in a dummy time, and increment it
                key = str(dummyTime) + '_' + c.name
                timeSortHash[key] = {k: (c, r)}
                logger.debug("Set timeSortHash['%s'] = %s", key, {k: (c, r)})
                dummyTime += timedelta(seconds=1)
                logger.debug('dummyTime = %s', dummyTime)

    # Build list of hashes to pass to the campaigns.html template
    camList = []
    sum_MeasuredParameter_count = 0
    sum_SampledParameter_count = 0
    for d in sorted(list(timeSortHash.keys()), reverse=True):
        logger.debug("d = %s, timeSortHash[d] = %s", d, timeSortHash[d])
        for k, (c, r) in list(timeSortHash[d].items()):
            logger.debug(k)
            logger.debug(c)
            description = ''
            startdate = ''
            enddate = ''
            if c.description:
                description = c.description
            if c.startdate:
                startdate = c.startdate.strftime('%d %b %Y')
            if c.enddate:
                enddate = c.enddate.strftime('%d %b %Y')

            sum_SampledParameter_count += int(r.get('SampledParameter_count', 0))
            sum_MeasuredParameter_count += int(r.get('MeasuredParameter_count', 0))
            camList.append({'name': c.name, 'dbAlias': k, 'description': description,
                            'startdate': startdate, 'enddate': enddate,
                            'MeasuredParameter_count': r.get('MeasuredParameter_count', ''),
                            'SampledParameter_count': r.get('SampledParameter_count', ''),
                            'Parameter_count': r.get('Parameter_count', ''),
                            'Platform_count': r.get('Platform_count', ''),
                            'Activity_count': r.get('Activity_count', ''),
                            'minutes_to_load': r.get('minutes_to_load', ''),
                            'loadlog': r.get('load_logfile', '')})

    logger.debug("camList = %s", camList)
    logger.info(f"Total SampledParameter_count = {sum_SampledParameter_count}")
    logger.info(f"Total MeasuredParameter_count = {sum_MeasuredParameter_count}")
    if format == 'json':
        return HttpResponse(json.dumps(camList, cls=encoders.STOQSJSONEncoder), 'application/json')
    elif format == 'count':
        return HttpResponse(len(camList), mimetype='text/plain')
    else:
        return render(request, 'campaigns.html', context={'cList': camList})


def showActivitiesMBARICustom(request):
    '''Present list of Activities in the database.  Unlike showDatabase(), show show the Activities and their
    local attributes, no counts, or delete link.  This is so that it will display more quickly.

    '''

    aList = mod.Activity.objects.all().order_by('-startdate')       # Reverse order so that they pop off list in order

    # Construct our own Act activity list with an enhanced comment
    actList = []
    for a in aList:
        act = Act()

        if a.campaign:
            act.campaignName = a.campaign.name
        if a.platform:
            act.platformName = a.platform.name
        if a.activitytype:
            act.activityTypeName = a.activitytype.name
        act.id = a.id
        act.name = a.name
        act.startdate = a.startdate
        act.isostartdate = a.startdate.strftime('%Y%m%dT%H%M%S')
        if a.enddate:
            act.enddate = a.enddate
            act.isoenddate = a.enddate.strftime('%Y%m%dT%H%M%S')

        # Pull out information from initial comment to construct preview links to the data - uses 'syntactic surgar' and knowlegde of the comment that DAPloader creates
        # It's probably better to do this in the template file - but I know how to do it this way
        try:
            mparms = a.comment.split(':')[1].split('.')[0].split(' ')
        except IndexError:
            # Empty comment, append Activity and continue
            actList.append(act)
            continue

        # Note:  This is really bad form: mixing html style here...
        #        We'd like this information, and it should probably be added to the model...
        # commStr = '<b>' + a.comment.split(':')[0] + '</b>'
        commStr = ''
        depthQuery = 'depth/0/300'
        commStr += '<b>Parameters</b> (Sample links here are for /%s)\n<table border="0">' % depthQuery
        for mp in mparms:
            if not mp:
                continue
            commStr += '\n<tr><td><p class="smallerText">%s:</p></td>' % mp

stoqs/stoqs/templates/stoqs/campaigns.html
{% load humanize %}
<!DOCTYPE html> <!--  HTML5 Doctype -->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1" />
    <title>Campaign List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Spatial Temporal Oceanographic Query System - Campaign List">
    <meta name="author" content="Mike McCann, MBARI">

    <!-- The styles -->
    <link href="{{STATIC_URL}}bootstrap/css/bootstrap.css" rel="stylesheet">
    <style>
        body {
            padding-top: 35px;  /* 35px to make the container go all the way to the bottom of the topbar */
        }
    </style>
    <link href="{{STATIC_URL}}bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
    <link type="text/css" href="{{ STATIC_URL }}jquery/css/custom-theme/jquery-ui-1.8.17.custom.css" rel="stylesheet" />    
    

    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- The fav and touch icons -->
    <link rel="shortcut icon" href="{{STATIC_URL}}media/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{STATIC_URL}}bootstrap/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{STATIC_URL}}bootstrap/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="{{STATIC_URL}}bootstrap/ico/apple-touch-icon-57-precomposed.png">

    <!-- Google Analytics -->
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-29827353-2']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner" style="height:34px;">
        <div class="container container-fixed-bot" style="margin-left:20px;">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="http://www.mbari.org" style="padding-top:4px;"><img src="{{STATIC_URL}}images/new_mbari_logo.png"></a>
          <a class="brand" href="#">STOQS</a>
        </div>
      </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <h2>Campaigns on this server (in reverse time order)</h2>
                    <table class="table table-condensed table-bordered">
                        <thead>
                            <tr><th>Database Alias</th><th>Name</th><th>Description</th><th>Start (GMT)</th><th>End (GMT)</th>
                                <th>Platform count</th><th>Parameter count</th><th>Activity count</th>
                                <th>MP count</th><th>SP count</th><th>Loading Time (minutes)</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for c in cList %}
                            <tr>
                            <td>{{ c.dbAlias }}</td>
                            <td><a href="{{site_uri}}{% url 'stoqs:stoqs-query-ui' dbAlias=c.dbAlias %}">{{ c.name }}</a></td><td>{{ c.description }}</td>
                            <td>{{ c.startdate }}</td><td>{{ c.enddate }}</td>
                            <td>{{ c.Platform_count }}</td><td>{{ c.Parameter_count }}</td><td>{{ c.Activity_count }}</td>
                            <td>{{ c.MeasuredParameter_count|intcomma }}</td><td>{{ c.SampledParameter_count|intcomma }}</td>
                            <td><a href="{{ c.loadlog }}">{{ c.minutes_to_load }}</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </div>
        </div>

    </div> <!-- container-fluid -->

  </body>
</html>